### ISSUE TITLE
Patch size difference from paper

### ISSUE THREAD

**Issue by arkel23** [aanna0701/SPT_LSA_ViT#6]
Hello. First of all, thanks for sharing this great repository! I have a question. In the [paper](https://arxiv.org/abs/2112.13492), in section 4.1.2 when you describe the models you mention using patch size 8 for small scale experiments (image size 32 I guess) and patch size 16 for Swin/PIT. But in the source code you set it to 4 for ViTs, and to 2 for Swin/PIT if image size is 32, or 8 and 4 if image size is larger, respectively. So which one did you actually use?
https://github.com/aanna0701/SPT_LSA_ViT/blob/main/models/create_model.py#L9

**Comment by ghost** [comment]
If i may say one thing, i used patch size 4 today with a vit and got >95% result on malaria cell classification, dataset is only ~27k imgs, patchsize 6 and 8 gave lower results nearer to 91-93%

**Comment by aanna0701** [comment]
sorry. It seems that the description on the paper is wrong. I'll edit it like this:
"The patch size of the patch embedding was set so that the number of tokens is 8. and the patch size of ViTs using pooling layers such as Swin and PiT was set to so that the number of tokens is 16."
So if the image size is 32, the patch size is 4 for ViT and 2 for swin.

**Comment by arkel23** [comment]
Oh okay thanks for the information! Great paper btw!
